SELECT
    WORKS_ON.EMPLOYEE_ID,
    EMPLOYEES.LAST_NAME,
    EMPLOYEES.SALARY,
    SUM(WORKS_ON.END_DATE - WORKS_ON.START_DATE) AS "NrZile",
    COUNT(WORKS_ON.EMPLOYEE_ID) AS "Nr total proiecte"
FROM
    EMPLOYEES
    INNER JOIN WORKS_ON ON WORKS_ON.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID
WHERE
    WORKS_ON.PROJECT_ID IN (
        SELECT
            PROJECT.PROJECT_ID
        FROM
            PROJECT
            INNER JOIN WORKS_ON ON PROJECT.PROJECT_ID = WORKS_ON.PROJECT_ID
        GROUP BY
            PROJECT.PROJECT_ID,
            PROJECT.PROJECT_NAME
        HAVING
            COUNT(PROJECT.PROJECT_ID) < 7
    )
GROUP BY
    WORKS_ON.EMPLOYEE_ID,
    EMPLOYEES.LAST_NAME,
    EMPLOYEES.SALARY
ORDER BY
    WORKS_ON.EMPLOYEE_ID;