COMMIT;

UPDATE CAMPANIE_AAE SET VALOARE = 1.25 * VALOARE WHERE VALOARE IS NOT NULL;

SELECT
    COD_CAMPANIE,
    TITLU,
    DATA_START,
    DATA_END,
    NVL(TO_CHAR(VALOARE), 'Campanie Caritabila') AS VALOARE,
    COD_SPONSOR
FROM
    CAMPANIE_AAE;

ROLLBACK;