INSERT ALL
    INTO SPONSOR_AAE(COD_SPONSOR, NUME, EMAIL) VALUES (10, 'CISCO', 'cisco@gmail.com')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME) VALUES (20, 'KFC')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME, EMAIL) VALUES (30, 'ADOBE', 'adobe@adobe.com')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME) VALUES (40, 'BRD')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME, EMAIL) VALUES (50, 'VODAFONE', 'vdf@gmail.com')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME) VALUES (60, 'BCR')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME) VALUES (70, 'SAMSUNG')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME, EMAIL) VALUES (80, 'IBM', 'ibm@ibm.com')
    INTO SPONSOR_AAE(COD_SPONSOR, NUME, EMAIL) VALUES (90, 'OMV', NULL)
    INTO SPONSOR_AAE(COD_SPONSOR, NUME, EMAIL) VALUES (100, 'ENEL', NULL)
SELECT * FROM DUAL;

SELECT * FROM SPONSOR_AAE;

INSERT ALL
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, VALOARE, COD_SPONSOR) VALUES (1, 'CAMP1', TO_DATE('20-06-2024', 'dd-mm-yyyy'), 1200, 10)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, VALOARE, COD_SPONSOR) VALUES (2, 'CAMP2', TO_DATE('25-07-2024', 'dd-mm-yyyy'), 3400, 20)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, COD_SPONSOR) VALUES (3, 'CAMP3', TO_DATE('10-06-2024', 'dd-mm-yyyy'), 30)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, COD_SPONSOR) VALUES (4, 'CAMP4', TO_DATE('20-06-2024', 'dd-mm-yyyy'), 40)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, VALOARE, COD_SPONSOR) VALUES (5, 'CAMP5', TO_DATE('05-06-2024', 'dd-mm-yyyy'), 2200, 50)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, COD_SPONSOR) VALUES (6, 'CAMP6', TO_DATE('15-08-2024', 'dd-mm-yyyy'), 60)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, VALOARE, COD_SPONSOR) VALUES (7, 'CAMP7', TO_DATE('02-09-2024', 'dd-mm-yyyy'), 5500, 70)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, COD_SPONSOR) VALUES (8, 'CAMP8', TO_DATE('10-10-2024', 'dd-mm-yyyy'), 20)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, VALOARE, COD_SPONSOR) VALUES (9, 'CAMP9', TO_DATE('10-06-2024', 'dd-mm-yyyy'), 4000, 30)
    INTO CAMPANIE_AAE(COD_CAMPANIE, TITLU, DATA_END, VALOARE) VALUES (10, 'CAMP10', TO_DATE('25-09-2024', 'dd-mm-yyyy'), 3500)
SELECT * FROM DUAL;

SELECT * FROM CAMPANIE_AAE;