CREATE TABLE SPONSOR_AAE (
    COD_SPONSOR NUMBER NOT NULL,
    NUME VARCHAR2(255) UNIQUE NOT NULL,
    EMAIL VARCHAR2(255) UNIQUE,
    CONSTRAINT COD_SPONSOR_PRIMARY_KEY PRIMARY KEY (COD_SPONSOR)
);

CREATE TABLE CAMPANIE_AAE (
    COD_CAMPANIE NUMBER NOT NULL,
    TITLU VARCHAR2(255) NOT NULL,
    DATA_START DATE DEFAULT SYSDATE NOT NULL,
    DATA_END DATE NOT NULL,
    VALOARE NUMBER,
    COD_SPONSOR NUMBER,
    CONSTRAINT COD_CAMPANIE_PRIMARY_KEY PRIMARY KEY (COD_CAMPANIE),
    CONSTRAINT DATA_END_CONSTRAINT CHECK (DATA_END > DATA_START),
    CONSTRAINT COD_SPONSOR_FOREIGN_KEY FOREIGN KEY (COD_SPONSOR) REFERENCES SPONSOR_AAE(COD_SPONSOR)
);